class_name HenchmanRecruitmentService
extends RefCounted

const CAMPAIGN_DAY_TICKS: int = 1440
const CAMPAIGN_MONTH_DAYS: int = 30
const CAMPAIGN_MONTH_TICKS: int = CAMPAIGN_DAY_TICKS * CAMPAIGN_MONTH_DAYS

const NAMES: Array[String] = [
	"Vorn Ash-Eater", "Rask Bloodhand", "Torra Flint-Breaker", "Hedda Wolfscar",
	"Kjell Bone-Taker", "Yrsa Black-Tooth", "Sten Red-Mane", "Runa Iron-Eye",
	"Brand Hollow-Eye", "Edda Crow-Bone", "Gorm Ash-Spear", "Siv Red-Hand",
]
const PORTRAITS: Array[StringName] = [&"portrait.reaver.marauder"]

var _catalogue: ContentCatalogue
var _personnel_capacity_service: PersonnelCapacityService


func configure(catalogue: ContentCatalogue, personnel_capacity_service: PersonnelCapacityService = null) -> void:
	_catalogue = catalogue
	_personnel_capacity_service = personnel_capacity_service


func ensure_market_candidate(campaign: CampaignState) -> bool:
	if campaign == null or _catalogue == null:
		return false
	var current_month_index: int = market_month_index(campaign.campaign_tick)
	if campaign.recruitment_market_month_index < 0:
		# Preserve any candidates already generated by the previous hotfix when an
		# existing save is migrated. A depleted old market also remains depleted until
		# the next monthly boundary instead of refilling merely because the game loaded.
		campaign.recruitment_market_month_index = current_month_index
		if campaign.recruitment_market_revision <= 0:
			return refresh_market_candidate(campaign, current_month_index)
		campaign.revision += 1
		return true
	if current_month_index > campaign.recruitment_market_month_index:
		return refresh_market_candidate(campaign, current_month_index)
	return false


func refresh_market_if_due_candidate(campaign: CampaignState) -> bool:
	return ensure_market_candidate(campaign)


func refresh_market_candidate(campaign: CampaignState, month_index: int = -1) -> bool:
	if campaign == null or _catalogue == null:
		return false
	var resolved_month_index: int = (
		market_month_index(campaign.campaign_tick)
		if month_index < 0
		else month_index
	)
	campaign.recruitment_market_revision += 1
	campaign.recruitment_market_month_index = resolved_month_index
	campaign.recruitment_offers_by_id.clear()
	var protagonist: PersistentCharacterState = campaign.get_character(campaign.protagonist_character_id)
	var definitions: Array[HenchmanRecruitmentDefinition] = []
	for definition: HenchmanRecruitmentDefinition in _catalogue.recruitment_definitions():
		if protagonist != null and protagonist.class_rank(definition.base_class_id) >= definition.required_protagonist_class_level:
			definitions.append(definition)
	if definitions.is_empty():
		campaign.revision += 1
		return true
	var rng := RandomNumberGenerator.new()
	# The market revision keeps consecutive refreshes distinct; the authored 30-day
	# month index makes the result stable for a saved campaign month.
	rng.seed = (
		int(campaign.campaign_seed)
		^ int(campaign.recruitment_market_revision * 104729)
		^ int((resolved_month_index + 1) * 130363)
	)
	var used_names: Dictionary = {}
	for character: PersistentCharacterState in campaign.get_characters():
		used_names[character.display_name] = true
	var offer_sequence: int = 1
	for definition: HenchmanRecruitmentDefinition in definitions:
		for index: int in range(definition.market_offer_count):
			var offer := HenchmanRecruitmentOfferState.new()
			offer.offer_id = StringName("recruit.offer.%04d.%02d" % [campaign.recruitment_market_revision, offer_sequence])
			offer.recruitment_definition_id = definition.recruitment_id
			offer.generated_identity_seed = int(rng.randi())
			offer.candidate_name = _random_unique_name(rng, used_names, offer_sequence)
			offer.portrait_id = PORTRAITS[rng.randi_range(0, PORTRAITS.size() - 1)]
			offer.market_revision = campaign.recruitment_market_revision
			campaign.recruitment_offers_by_id[offer.offer_id] = offer
			offer_sequence += 1
	campaign.revision += 1
	return true


func offers(campaign: CampaignState) -> Array[HenchmanRecruitmentOfferState]:
	return campaign.get_recruitment_offers() if campaign != null else []


func market_status(campaign: CampaignState) -> Dictionary:
	if campaign == null:
		return {
			"month_index": 0,
			"next_refresh_tick": CAMPAIGN_MONTH_TICKS,
			"remaining_ticks": CAMPAIGN_MONTH_TICKS,
			"next_refresh_day": CAMPAIGN_MONTH_DAYS + 1,
		}
	var active_month_index: int = campaign.recruitment_market_month_index
	if active_month_index < 0:
		active_month_index = market_month_index(campaign.campaign_tick)
	var next_refresh_tick: int = (active_month_index + 1) * CAMPAIGN_MONTH_TICKS
	return {
		"month_index": active_month_index,
		"next_refresh_tick": next_refresh_tick,
		"remaining_ticks": maxi(0, next_refresh_tick - campaign.campaign_tick),
		"next_refresh_day": next_refresh_tick / CAMPAIGN_DAY_TICKS + 1,
		"month_length_days": CAMPAIGN_MONTH_DAYS,
	}


func preview_offer(campaign: CampaignState, offer_id: StringName) -> Dictionary:
	var offer: HenchmanRecruitmentOfferState = campaign.get_recruitment_offer(offer_id) if campaign != null else null
	var definition: HenchmanRecruitmentDefinition = (
		_catalogue.recruitment_definition(offer.recruitment_definition_id)
		if offer != null and _catalogue != null else null
	)
	var reasons: Array[String] = []
	if campaign == null or offer == null or definition == null:
		reasons.append("This recruit offer is no longer available.")
		return {"eligible": false, "reasons": reasons, "reason": reasons[0]}
	var protagonist: PersistentCharacterState = campaign.get_character(campaign.protagonist_character_id)
	if protagonist == null or protagonist.class_rank(definition.base_class_id) < definition.required_protagonist_class_level:
		reasons.append("The protagonist has not unlocked this class of henchman.")
	if not definition.required_facility_id.is_empty() and not _operational_facility(campaign, definition.required_facility_id, 1):
		reasons.append("Requires an operational %s." % _short_id(definition.required_facility_id))
	if _personnel_capacity_service != null:
		var capacity: Dictionary = _personnel_capacity_service.snapshot(campaign)
		if int(capacity.get("used", 0)) + _legacy_reserved_capacity(campaign) + definition.roster_capacity_cost > int(capacity.get("maximum", 0)):
			reasons.append("Personnel capacity is full.")
	elif campaign.active_roster_count() + _legacy_reserved_capacity(campaign) + definition.roster_capacity_cost > campaign.roster_capacity:
		reasons.append("Roster capacity is full.")
	for raw_id: Variant in definition.resource_costs.keys():
		var resource_id := StringName(raw_id)
		var required: int = int(definition.resource_costs[raw_id])
		if campaign.resources.amount(resource_id) < required:
			reasons.append("Requires %d %s." % [required, String(resource_id).capitalize()])
	return {
		"eligible": reasons.is_empty(), "reasons": reasons,
		"reason": reasons[0] if not reasons.is_empty() else "Available",
		"offer": offer, "definition": definition,
		"costs": definition.resource_costs.duplicate(true),
		"duration_ticks": 0,
		"instant": true,
	}


func start_candidate(campaign: CampaignState, offer_id: StringName) -> OperationResult:
	var preview_data: Dictionary = preview_offer(campaign, offer_id)
	if not bool(preview_data.get("eligible", false)):
		return OperationResult.fail(&"recruitment_ineligible", String(preview_data.get("reason", "Recruitment is unavailable.")))
	var offer: HenchmanRecruitmentOfferState = preview_data.get("offer") as HenchmanRecruitmentOfferState
	var definition: HenchmanRecruitmentDefinition = preview_data.get("definition") as HenchmanRecruitmentDefinition
	if offer == null or definition == null:
		return OperationResult.fail(&"recruitment_data_changed", "The selected recruit changed before confirmation.")
	for raw_id: Variant in definition.resource_costs.keys():
		if not campaign.resources.add(StringName(raw_id), -int(definition.resource_costs[raw_id])):
			return OperationResult.fail(&"recruitment_cost_changed", "Recruitment resources changed before confirmation.")
	var created: OperationResult = _create_recruit_candidate(
		campaign,
		definition,
		offer.candidate_name,
		offer.portrait_id
	)
	if not created.success:
		return created
	campaign.recruitment_offers_by_id.erase(offer.offer_id)
	campaign.revision += 1
	var character: PersistentCharacterState = created.data as PersistentCharacterState
	return OperationResult.ok(
		character,
		"%s joined the Roster immediately." % offer.candidate_name
	)


func advance_candidate(campaign: CampaignState) -> Array[StringName]:
	# Compatibility migration for saves made while recruitment was timed. New hires
	# never create a RecruitmentProject; any old unapplied project completes as soon
	# as there is roster space, without waiting for its former completion tick.
	var completed: Array[StringName] = []
	if campaign == null or _catalogue == null:
		return completed
	for project: HenchmanRecruitmentProjectState in campaign.get_recruitment_projects():
		if project.applied or project.status in [HenchmanRecruitmentProjectState.STATUS_APPLIED, HenchmanRecruitmentProjectState.STATUS_CANCELLED]:
			continue
		var definition: HenchmanRecruitmentDefinition = _catalogue.recruitment_definition(project.recruitment_definition_id)
		if definition == null:
			continue
		if _personnel_capacity_service != null:
			var capacity: Dictionary = _personnel_capacity_service.snapshot(campaign)
			if int(capacity.get("used", 0)) + definition.roster_capacity_cost > int(capacity.get("maximum", 0)):
				continue
		elif campaign.active_roster_count() + definition.roster_capacity_cost > campaign.roster_capacity:
			continue
		var created: OperationResult = _create_recruit_candidate(
			campaign,
			definition,
			project.candidate_name,
			project.portrait_id
		)
		if not created.success:
			continue
		var character: PersistentCharacterState = created.data as PersistentCharacterState
		project.result_character_id = character.character_id
		project.applied = true
		project.status = HenchmanRecruitmentProjectState.STATUS_APPLIED
		project.revision += 1
		completed.append(character.character_id)
	if not completed.is_empty():
		campaign.revision += 1
	return completed


func _create_recruit_candidate(
		campaign: CampaignState,
		definition: HenchmanRecruitmentDefinition,
		candidate_name: String,
		portrait_id: StringName
) -> OperationResult:
	if campaign == null or definition == null:
		return OperationResult.fail(&"recruitment_data_missing", "The recruit could not be created.")
	var template: CharacterTemplateDefinition = _catalogue.character_template(definition.resulting_character_template_id)
	if template == null:
		return OperationResult.fail(&"recruitment_template_missing", "The recruit's character template is missing.")
	var character_id := campaign.allocate_recruit_character_id(definition.career_id)
	var character := CharacterFactory.create_player_character(template, character_id, candidate_name)
	character.persistence_scope = PersistentCharacterState.PERSISTENCE_CAMPAIGN
	character.portrait_override_id = portrait_id
	character.base_class_id = definition.base_class_id
	character.class_ranks[definition.base_class_id] = definition.starting_level
	character.career_id = definition.career_id
	var career: TroopCareerDefinition = _catalogue.troop_career(definition.career_id)
	character.base_henchman_type_id = career.base_henchman_type_id if career != null else &""
	character.current_troop_type_id = character.base_henchman_type_id
	character.troop_tier = 0
	character.xp = definition.starting_xp
	character.add_history("Recruited at the Fifth-God Ruin as a Level 1 %s." % definition.display_name)
	if not campaign.add_character(character):
		return OperationResult.fail(&"recruitment_character_rejected", "The new recruit could not be added to the Roster.")
	CharacterFactory.add_default_loadout_to_campaign(campaign, character, template)
	return OperationResult.ok(character)


func _legacy_reserved_capacity(campaign: CampaignState) -> int:
	var result: int = 0
	for project: HenchmanRecruitmentProjectState in campaign.get_recruitment_projects():
		if not project.applied and project.status not in [HenchmanRecruitmentProjectState.STATUS_CANCELLED, HenchmanRecruitmentProjectState.STATUS_APPLIED]:
			result += 1
	return result


static func market_month_index(campaign_tick: int) -> int:
	return maxi(0, campaign_tick) / CAMPAIGN_MONTH_TICKS


static func _short_id(value: StringName) -> String:
	return String(value).get_slice(".", String(value).count(".")).replace("_", " ").capitalize()


static func _operational_facility(campaign: CampaignState, definition_id: StringName, minimum_level: int) -> bool:
	if definition_id.is_empty():
		return true
	if campaign == null or campaign.stronghold == null:
		return false
	for facility: StrongholdFacilityState in campaign.stronghold.get_facilities():
		if facility.definition_id == definition_id and facility.condition == StrongholdFacilityState.CONDITION_OPERATIONAL and facility.level >= minimum_level:
			return true
	return false


static func _random_unique_name(rng: RandomNumberGenerator, used_names: Dictionary, fallback_index: int) -> String:
	for attempt: int in range(NAMES.size() * 2):
		var candidate: String = NAMES[rng.randi_range(0, NAMES.size() - 1)]
		if not used_names.has(candidate):
			used_names[candidate] = true
			return candidate
	var fallback: String = "Reaver Recruit %02d" % fallback_index
	used_names[fallback] = true
	return fallback
